### ISSUE TITLE
Publicly exposed Vuplex 3D WebView

### ISSUE THREAD

**Issue by binarynate** [metafi-nft/metafi-unity-sdk#1]
Hi, @arvindbr95 👋🏻. This is Nate, the Founder of Vuplex. First, thanks again using 3D WebView! I really appreciate your business and partnership. I'm opening this issue because your repo includes the assets for [3D WebView](https://vuplex.com), which aren't allowed to be shared publicly according to [its license](https://support.vuplex.com/articles/commercial-library-license). To resolve this issue, can you please remove the files in the Assets/Vuplex folder from this repo's Git history?

https://github.com/metafi-nft/metafi-unity-sdk/tree/df0c724c202136cdbd071731ad4e964f5c38aba1/Assets/Vuplex/WebView

**Comment by binarynate** [comment]
Hey, @arvindbr95 . It's been a week and I haven't heard back from you. Can you please remove this content? If I don't hear back from you soon, then I'll have to contact GitHub about taking it down.

**Comment by arvindbr95** [comment]
Working on it with the GitHub team as per https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

**Comment by binarynate** [comment]
Thank you, @arvindbr95 ! I appreciate your response and cooperation.

**Comment by arvindbr95** [comment]
References and cache cleared by Github team. Closing

**Comment by binarynate** [comment]
Thanks!
